version: '3.8'  # You can use other versions compatible with Docker

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mediafusion:
    build:
      # context: ./apps/MediaFusion
      context: .
      dockerfile: ./apps/MediaFusion/Dockerfile
    container_name: media-fusion
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
    driver: local